pool:
  vmImage: ubuntu-latest

trigger:
  - master

stages:
  - stage: buildmac 
    jobs:
      - job: printnumbers
        steps:
          - script: echo 1
          - script: echo 2
          - script: echo 3
          - script: echo 4
          - script: echo 5    