pool: 
  name: default

trigger: 
  - azuredevops 

steps:
  - script: sudo apt update && sudo apt install software-properties-common && sudo add-apt-repository --yes --update ppa:ansible/ansible && sudo apt install ansible
  - script: ansible-playbook -i host java17.yaml
 
    