- name: install java server on ubuntu
  hosts: localhost
  become: yes
  tasks: 
    - name: install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: latest
        update_cache : true